### ISSUE TITLE
Simulation fails due to MMCLAB ERROR (1001): Unknown in unit mmc_cl_utils.c:148

### ISSUE THREAD

**Issue by lewisfish** [COTILab/BlenderPhotonics#2]
Hi, I'm trying to use BlenderPhotonics. I can create the meshes, assign optical properties etc. However, when I run the simulation it always crashes.
I had to compile mmclab myself due to missing libraries, and it complained that there was no mmcsrcdomain.m until I added mmc/matlab to OCTAVE's path.

Attached below is the output of Blender, for a scene with just the default cube.
Any help in getting this fixed would be appreciated!

```
Read prefs: /home/lewis/.config/blender/2.92/config/userpref.blend
Registering BlenderPhotonics
begin to generate mesh
MESH
LIGHT
CAMERA
Info: Deleted 2 object(s)
Warning: No intersections found
use exact intersection solver
generating tetrahedral mesh from closed surfaces ...
creating volumetric mesh from a surface mesh ...
volume mesh generation is complete
tdir = /tmp/iso2mesh-lewis/blenderphotonics
begin to save region mesh
maxtag =  1
begin to save whole volumic mesh.
tdir = /tmp/iso2mesh-lewis/blenderphotonics
tdir = /tmp/iso2mesh-lewis/blenderphotonics
saving complete.
Info: Deleted 1 object(s)
begin to import region mesh
Info: Deleted 1 object(s)
{'min': array([-1., -1., -1.]), 'max': array([1., 1., 1.])}
Begin to run MMC source transport simulation ...
pencil
param =

  scalar structure containing the fields:

    prop =

       0.00100   0.10000   0.00000   1.37000

    cfg =

      scalar structure containing the fields:

        srctype = pencil
        srcpos =

           0.00000   0.00000   1.20000

        srcdir =

           1   0   0   0

        srcparam1 =

           0   0   0   0

        srcparam2 =

           0   0   0   0

        nphoton =  10000
        unitinmm =  1
        tend =  0.0000000050000
        tstep =  0.0000000050000
        isreflect = 1
        isnormalized = 1
        method = elem
        outputtype = flux
        basisorder =  1
        debuglevel = TP
        gpuid = 1


tdir = /tmp/iso2mesh-lewis/blenderphotonics
searching initial element ...
Launching MMCLAB - Mesh-based Monte Carlo for MATLAB & GNU Octave ...
Running simulations for configuration #1 ...
mmc.nphoton=10000;
mmc.srctype='pencil';
mmc.srcpos=[0 0 1];
mmc.srcdir=[0 0 -1 0];
mmc.srcparam1=[0 0 0 0];
mmc.srcparam2=[0 0 0 0];
mmc.prop=1;
mmc.nn=20;
mmc.elem=[22,4];
mmc.ne=22;
mmc.tstart=0;
mmc.tend=5e-09;
mmc.tstep=5e-09;
mmc.isreflect=1;
mmc.isnormalized=0;
mmc.gpuid='1';
mmc.unitinmm=1;
mmc.outputtype='flux';
mmc.debuglevel='TP';
mmc.method='elem';
mmc.e0=3;
mmc.facenb=[22,4];
mmc.evol=22;
	done	1
simulating ...
MMCLAB ERROR (1001): Unknown in unit mmc_cl_utils.c:148
Error from thread (0): Unknown
	done	1
Python: Traceback (most recent call last):
  File "/home/lewis/.config/blender/2.92/scripts/addons/BlenderPhotonics-master/runmmc.py", line 143, in execute
    self.preparemmc()
  File "/home/lewis/.config/blender/2.92/scripts/addons/BlenderPhotonics-master/runmmc.py", line 101, in preparemmc
    oc.feval('blendermmc',os.path.join(outputdir,'mmcinfo.json'), os.path.join(outputdir,'meshdata.mat'), nargout=0)
  File "/home/lewis/anaconda3/envs/py37/lib/python3.7/site-packages/oct2py/core.py", line 387, in feval
    store_as=store_as, plot_dir=plot_dir)
  File "/home/lewis/anaconda3/envs/py37/lib/python3.7/site-packages/oct2py/core.py", line 588, in _feval
    raise Oct2PyError(msg)
oct2py.utils.Oct2PyError: Octave evaluation error:
error: fluxmin(2): out of bound 1
error: called from:
    blendermmc at line 94, column 26

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "/home/lewis/.config/blender/2.92/scripts/addons/BlenderPhotonics-master/runmmc.py", line 143, in execute
    self.preparemmc()
  File "/home/lewis/.config/blender/2.92/scripts/addons/BlenderPhotonics-master/runmmc.py", line 101, in preparemmc
    oc.feval('blendermmc',os.path.join(outputdir,'mmcinfo.json'), os.path.join(outputdir,'meshdata.mat'), nargout=0)
  File "/home/lewis/anaconda3/envs/py37/lib/python3.7/site-packages/oct2py/core.py", line 387, in feval
    store_as=store_as, plot_dir=plot_dir)
  File "/home/lewis/anaconda3/envs/py37/lib/python3.7/site-packages/oct2py/core.py", line 588, in _feval
    raise Oct2PyError(msg)
oct2py.utils.Oct2PyError: Octave evaluation error:
error: fluxmin(2): out of bound 1
error: called from:
    blendermmc at line 94, column 26

location: <unknown location>:-1
```

**Comment by lewisfish** [comment]
Okay, fixed that issue by removing the DUSE_OPENCL flag in the makefile.

However, I'm now running into the issue that fluxmin(2) is out of bounds. On inspection fluxmin has length 1.
Changing the 2 to a 1 allows the code to run to completion. 
However, the output is uniformly blue with no change in fluence.
I'm guessing my various fixes have broken something somewhere?

**Comment by fangq** [comment]
line 148 in mcx_cl_utils.c is this
```
    OCL_ASSERT((clGetPlatformIDs(0, NULL, &numPlatforms)));
```
which is the first line to call OpenCL functions. It appears that your system does not have opencl set up properly. what GPU do you use and whether you have installed the opencl support?

**Comment by fangq** [comment]
can you share your file `/tmp/iso2mesh-USER/blenderphotonics/mmccfg.mat` via dropbox/google drive link? my feeling is that your source does not launch any photon in the domain so the entire volume have 0 fluence.

**Comment by lewisfish** [comment]
> can you share your file `/tmp/iso2mesh-USER/blenderphotonics/mmccfg.mat` via dropbox/google drive link? my feeling is that your source does not launch any photon in the domain so the entire volume have 0 fluence.

I thought that might be the case, but embedding the source in the middle of the medium yields nothing.
I also tried copying the S. Jacques test case from the biorxiv paper and that yielded nothing as well.
I've uploaded the file [here](https://drive.google.com/file/d/17DbcN_UXXSPgwbqk-PRzIpZqOXIcfRYW/view?usp=sharing)

**Comment by lewisfish** [comment]
I've tried the demo_example_onecube.m using Octave and it gives 0 flux everywhere. I'm guessing this means that in building mmclab without the opencl flags I broke something?

**Comment by lewisfish** [comment]
I've now installed BlenderPhotonics on a machine with a GPU and it works. Had to rebuild the mex files and due to a missing liboctinterp.so, then remove a path from blender's default sys.path due to an issue with it importing the wrong version of numpy.

I'm not sure what caused the issue on the computer with no GPU, but I know it wasn't running any photons at all (no progress bar woth debug options TP enabled) so guessing that building without openCL support breaks things.
